{% set name = "xtb-python" %}
{% set version = "22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/xtb-python/releases/download/v{{ version }}/xtb-{{ version }}.tar.gz
  sha256: 7a59e7b783fc6e8b7328f55211de681e535a83991b07c4bab73494063f5e9018
  patches:
    - gh-114.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('c') }}    # [unix]
    - {{ stdlib('m2w64_c') }}    # [win]
    - cffi                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - meson-python                        # [build_platform != target_platform]
    - pkg-config
    - python                              # [build_platform != target_platform]
    - python-build                        # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
  host:
    - cffi
    - meson-python
    - pip
    - python
    - python-build
    - setuptools
    - xtb
  run:
    - cffi
    - numpy
    - python


test:
  imports:
    - xtb
    - xtb.libxtb
    - xtb.interface
  requires:
    - pytest
    - ase
    - qcelemental
    - setuptools  # needs pkg_resources
  commands:
    - pytest --pyargs xtb.test_interface -vv  # [build_platform == target_platform]

about:
  home: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/xtb
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - "COPYING"
    - "COPYING.LESSER"
  summary: 'Python API of the Extended Tight-Binding Program Package'
  doc_url: https://xtb-python.readthedocs.io/
  dev_url: https://github.com/grimme-lab/xtb-python

extra:
  recipe-maintainers:
    - awvwgk
