{% set name = "xtb-python" %}
{% set version = "20.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 37d0f6239c3fa536caeb3638a2ffb4f4070cb3cc2ca314be4504905f96c4aaf1

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - meson 0.53.*
    - ninja
    - python
    - cffi
    - pkg-config
  host:
    - python
    - pip
    - xtb
  run:
    - python
    - cffi
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('xtb', max_pin='x.x') }}


test:
  imports:
    - xtb
  requires:
    - pytest
    - ase
    - qcelemental
  commands:
    - pytest --pyargs xtb -vv

about:
  home: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/xtb
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - "COPYING"
    - "COPYING.LESSER"
  summary: 'Python API of the Extended Tight-Binding Program Package'
  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/grimme-lab/{{ name }}

extra:
  recipe-maintainers:
    - awvwgk
