{% set name = "xtb-python" %}
{% set version = "22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7a59e7b783fc6e8b7328f55211de681e535a83991b07c4bab73494063f5e9018
  patches:
    - xtb.patch

build:
  number: 0
  skip: True  # [win or (osx and (python_impl == 'cpython' and py<38))]

requirements:
  build:
    - {{ compiler('c') }}
    - meson 0.53.*
    - ninja
    - python
    - cffi
    - pkg-config
  host:
    - python
    - pip
    - xtb
  run:
    - python
    - cffi
    - {{ pin_compatible('numpy') }}


test:
  imports:
    - xtb
  requires:
    - pytest
    - ase
    - qcelemental
    - setuptools
  commands:  # [not (python_impl == 'pypy' and py<37)]
    - pytest --pyargs xtb -vv  # [not (python_impl == 'pypy' and py<37)]

about:
  home: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/xtb
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - "COPYING"
    - "COPYING.LESSER"
  summary: 'Python API of the Extended Tight-Binding Program Package'
  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/grimme-lab/{{ name }}

extra:
  recipe-maintainers:
    - awvwgk
